name: Hello Testing
# This workflow is triggered on pushes to the repository
# new comment 1
on: [push]

jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create a binary file
        run: make
      - name: exacute action
        run: ./hello
      - uses: actions/download-artifact@v1
        with:
          name: hello-artifact


